apiVersion: v1
kind: Pod
metadata:
  name: k8s
  labels:
    app: k8s-app
spec:
  containers:
    - name: c1
      image: devapa/lila:hotel
      ports:
        - containerPort: 80



    <h1> SERVICE.YAML FILE


apiVersion: v1
kind: Service
metadata:
  name: svc-k8s
spec:
  type: NodePort
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
